### ISSUE TITLE
Apache Maven icon 

### ISSUE THREAD

**Issue by aashu4uiit** [cloudskew/cloudskew#109]
Can you please add this 
https://upload.wikimedia.org/wikipedia/commons/0/0b/Maven_logo.svg

**Comment by mithunshanbhag** [comment]
The linked SVG image above cannot be used since Cloudskew only uses abstract mark image (and not word marks).

Also unfortunately, [the official abstract mark SVGs](http://maven.apache.org/images/) made available by the Apache Maven project are > 50 KB in size (too large to include, most icons are 2 - 5 KB in size). 

Hence, regrettably, the icon cannot be added.

**Workaround**: However, users can always upload them as custom images (PNGs, JPGs supported).

![image](https://user-images.githubusercontent.com/2327905/89308269-aed3b980-d68f-11ea-9929-c84df96fd4c0.png)
