### ISSUE TITLE
Setting to disable auto-save

### ISSUE THREAD

**Issue by chaosmonster** [cloudskew/cloudskew#131]
**Is your feature request related to a problem? Please describe.**
Cloudskew looks like a promising tool. Unfortunately some companies don't allow to store the data on unsecured databases. 

**Describe the solution you'd like**
For those a possibility to use cloudskew in an "offline" mode without auto-save would be really helpful

**Comment by mithunshanbhag** [comment]
Hi @chaosmonster,

Unfortunately, at present time, there are no plans to disable auto-save (especially since this is critical to several upcoming features like snapshots, versioning etc).

However, for organizations, there will be an enterprise version of cloudskew coming later (with features such as choose-your-own-storage, bring-your-own-encryption-keys, sign-in-with-company-credentials, collaborative-editing-with-rbac etc).
