### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by msdollah1** [cloudskew/cloudskew#157]
I upgraded my account and it looks like I was charged twice. Can you clear this? Also, it processed the payments but I don't have upgraded access. Can you take care of this?

**Comment by mithunshanbhag** [comment]
Hi @msdollah1: Yes, I can see that you were charged twice. Looks like something went wrong in our system. Apologies for the bad experience. 

I'll reverse (refund) one of the transactions and enable upgraded access (professional tier). 

Will circle back in a bit as soon as this is done.

Thanks,
-Mithun

**Comment by mithunshanbhag** [comment]
Hi @msdollah1: One of  your payments have now been refunded, and your account has now been upgraded to professional tier.

![image](https://user-images.githubusercontent.com/2327905/200587678-198753ec-95c1-4722-91b9-11a20ae38ae3.png)

Please note that it may take 5 - 10 business days for the refund to arrive in your account. 

You should have also received an automated email from Stripe payment gateway regarding the refund.

Once again, my apologies for the negative experience. I'm still investigating the telemetry to narrow down the root cause of the issue.
