### ISSUE TITLE
Make connectors/arrows easy to find.

### ISSUE THREAD

**Issue by JasonBSteele** [cloudskew/cloudskew#17]
It's laborious to have to separately add connectors. I would like to be able to do it from an icon, either from its context menu or by selecting it and a symbol appearing near it which when clicked adds a connector to it already attached at the non-arrow end.

**Comment by mithunshanbhag** [comment]
Hi @JasonBSteele, thanks for the good feedback. 

Yes, I agree that finding and using the connectors should be easier. 

Making notes of the possible alternatives:
* Sticky the connectors group at the top of the icon palette (since they tend to be the most frequently used). 
* The top menu can expose a drop-down with the various connector types.
* Selecting/highlighting an icon should enable outgoing connectors (either via the context menu or thumbs). 

Open to other ideas, suggestions.

**Comment by JasonBSteele** [comment]
I personally like the third suggestion with thumbnails.

**Comment by mithunshanbhag** [comment]
**Update**: Connectors, Shapes and Text are now stickied to the top of the icon palette bar.

![image](https://user-images.githubusercontent.com/2327905/71581254-5dc47b80-2b2a-11ea-9df4-e0f798061a86.png)

**Comment by mithunshanbhag** [comment]
**Update**: It is now possible to attach connectors to a selected symbol via the context menu.

![image](https://user-images.githubusercontent.com/2327905/71626021-ffbe9380-2c10-11ea-9b44-b54928c6fce7.png)

**Comment by mithunshanbhag** [comment]
Closing this issue two possible solutions are now available: 
* connectors stickied to top of icon palette
* connectors can be attached to selected icon via context menu.
