### ISSUE TITLE
Azure Monitor Icon is all black

### ISSUE THREAD

**Issue by iLikeAzureSQL** [cloudskew/cloudskew#34]
**Describe the bug**
Azure Monitor icon is not showing properly, it's all black

**To Reproduce**
Grab Azure Monitor Icon

**Expected behavior**

**Screenshots**
If possible, add screenshots and/or screen recordings which capture the issue. These greatly help investigations.
![image](https://user-images.githubusercontent.com/16943754/72632773-dccbf900-390b-11ea-98d9-1ba721b751bd.png)

**Errors in browser console**
If you observe any errors in the browser console, please paste those here.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, firefox]
 - OS: [e.g. windows10, macOS]

**Additional details**
Add any other details about the problem here.

**Comment by mithunshanbhag** [comment]
Hi @iLikeAzureSQL: Thanks for reporting this issue. Very likely, it could be because of colliding CSS class names in the loaded symbols (SVG files). 

What icons are currently loaded on the canvas? 

Would it be possible to post a full screenshot of the diagram canvas? Will make it easier to troubleshoot.

**Comment by mithunshanbhag** [comment]
Fix has been pushed to production 

You will however need to delete any existing azure monitor icons from your diagrams and re-add them. 

Closing this bug, please reactivate if issue still persists for you.
